# Generated by Django 5.2 on 2025-05-06 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="A2AAgent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="代理名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("endpoint_url", models.URLField(verbose_name="端点URL")),
                (
                    "agent_card_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Agent Card URL"
                    ),
                ),
                (
                    "agent_card_content",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Agent Card内容"
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="认证类型"
                    ),
                ),
                (
                    "auth_config",
                    models.JSONField(blank=True, null=True, verbose_name="认证配置"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "last_checked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后检查时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="a2a_agents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "A2A代理",
                "verbose_name_plural": "A2A代理",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("definition", models.JSONField(verbose_name="工作流定义")),
                (
                    "workflow_type",
                    models.CharField(
                        default="standard", max_length=50, verbose_name="工作流类型"
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流",
                "verbose_name_plural": "工作流",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "instance_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="实例ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="实例名称"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "已创建"),
                            ("running", "运行中"),
                            ("paused", "已暂停"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("canceled", "已取消"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_step_index",
                    models.IntegerField(default=0, verbose_name="当前步骤索引"),
                ),
                (
                    "context",
                    models.JSONField(blank=True, null=True, verbose_name="上下文数据"),
                ),
                (
                    "output",
                    models.JSONField(blank=True, null=True, verbose_name="输出数据"),
                ),
                ("error", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_instances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_workflow_instances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="启动者",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="workflow.workflow",
                        verbose_name="工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流实例",
                "verbose_name_plural": "工作流实例",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_index", models.IntegerField(verbose_name="步骤索引")),
                ("step_id", models.CharField(max_length=255, verbose_name="步骤ID")),
                ("step_name", models.CharField(max_length=255, verbose_name="步骤名称")),
                ("step_type", models.CharField(max_length=50, verbose_name="步骤类型")),
                ("parameters", models.JSONField(default=dict, verbose_name="参数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(blank=True, null=True, verbose_name="输入数据"),
                ),
                (
                    "output_data",
                    models.JSONField(blank=True, null=True, verbose_name="输出数据"),
                ),
                ("error", models.TextField(blank=True, null=True, verbose_name="错误信息")),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "a2a_task_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="A2A任务ID"
                    ),
                ),
                (
                    "a2a_task_status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="A2A任务状态"
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflow.workflowinstance",
                        verbose_name="工作流实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流步骤",
                "verbose_name_plural": "工作流步骤",
                "ordering": ["instance", "step_index"],
                "unique_together": {("instance", "step_index")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("error", "错误"),
                            ("debug", "调试"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="workflow.workflowinstance",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="workflow.workflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流日志",
                "verbose_name_plural": "工作流日志",
                "ordering": ["-timestamp"],
            },
        ),
    ]
