# Generated by Django 5.2 on 2025-05-12 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the agent.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. A more detailed description of the agent and its purpose.",
                        null=True,
                    ),
                ),
                (
                    "provider_info",
                    models.JSONField(
                        blank=True,
                        help_text="Optional. Information about the agent provider (e.g., {'name': 'Platform X', 'url': 'https://platformx.com'}).",
                        null=True,
                    ),
                ),
                (
                    "service_url",
                    models.URLField(
                        help_text="The A2A service endpoint URL where this agent can be reached.",
                        max_length=1024,
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional. Describes supported A2A protocol features (e.g., {'streaming': false, 'pushNotifications': false}).",
                    ),
                ),
                (
                    "authentication_schemes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Authentication schemes supported by the agent. Example: [{'scheme': 'Bearer', 'description': 'Requires a Bearer token.'}]",
                    ),
                ),
                (
                    "a2a_version",
                    models.CharField(
                        default="1.0",
                        help_text="A2A protocol version this agent card conforms to.",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skill_id",
                    models.CharField(
                        help_text="Unique ID for the skill within the agent (e.g., 'generate-report', 'translate-text').",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the skill.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. A description of what the skill does.",
                        null=True,
                    ),
                ),
                (
                    "input_modes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Supported input content types for this skill. Example: ["application/json", "text/plain"]',
                    ),
                ),
                (
                    "output_modes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Supported output content types for this skill. Example: ["application/json", "text/plain"]',
                    ),
                ),
                (
                    "examples",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional. Examples of skill usage. Example: [{'description': 'Example 1', 'input': {'text': 'hello'}, 'output': {'translation': 'hola'}}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="agents.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Skill",
                "verbose_name_plural": "Agent Skills",
                "ordering": ["agent", "name"],
                "unique_together": {("agent", "skill_id")},
            },
        ),
    ]
