# Generated by Django 5.2 on 2025-05-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="is_a2a_compliant",
            field=models.BooleanField(
                default=False,
                help_text="Whether this agent is compliant with the A2A protocol.",
            ),
        ),
    ]
