# Generated by Django 5.2 on 2025-05-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_agent_is_a2a_compliant"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_type",
            field=models.CharField(
                default="custom",
                help_text="The type of agent (e.g., 'gpt', 'claude', 'custom').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether the agent is currently active and usable.",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="The specific model used by the agent (e.g., 'gpt-4', 'claude-3-sonnet').",
                max_length=255,
                null=True,
            ),
        ),
    ]
