# Generated by Django 5.2 on 2025-05-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0003_agent_agent_type_agent_is_active_agent_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="available_tools",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional. List of tool names the agent is allowed to use (e.g., ['calculator', 'web_search']).",
            ),
        ),
    ]
