# Generated by Django 5.2 on 2025-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0004_agent_available_tools"),
        (
            "knowledgebase",
            "0004_remove_knowledgebase_is_public_document_file_size_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="linked_knowledge_bases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge bases linked to this agent.",
                related_name="linked_agents",
                to="knowledgebase.knowledgebase",
            ),
        ),
    ]
