# Generated by Django 5.2 on 2025-05-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0005_agent_linked_knowledge_bases"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_software_version",
            field=models.CharField(
                blank=True,
                help_text="Version of the agent software/implementation. Corresponds to AgentCard.version.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="default_input_modes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional. Array of MIME types the agent generally accepts as input. Corresponds to AgentCard.defaultInputModes. Example: ['text/plain', 'application/json']. Defaults to ['text/plain'] if empty.",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="default_output_modes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional. Array of MIME types the agent generally produces as output. Corresponds to AgentCard.defaultOutputModes. Example: ['text/plain', 'application/json']. Defaults to ['text/plain'] if empty.",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="documentation_url",
            field=models.URLField(
                blank=True,
                help_text="Optional. URL to human-readable documentation for the agent. Corresponds to AgentCard.documentationUrl.",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional. Array of keywords or categories for discoverability. Corresponds to AgentSkill.tags in AgentCard. Example: ['finance', 'conversion'].",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="a2a_version",
            field=models.CharField(
                default="0.1.0",
                help_text="A2A protocol version this agent card claims to conform to (e.g., '0.1.0'). This is distinct from agent_software_version.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="authentication_schemes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Authentication schemes supported by the agent. For AgentCard.authentication, this should be transformed into {'schemes': ['SchemeName'], 'credentials': 'JSON string with details'}. Model stores an array of scheme objects, e.g., [{'type': 'Bearer', 'details': 'Requires a Bearer token.'}].",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional. Describes supported A2A protocol features. Corresponds to AgentCard.capabilities. Expected structure: {'streaming': false, 'pushNotifications': false, 'stateTransitionHistory': false}.",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="provider_info",
            field=models.JSONField(
                blank=True,
                help_text="Optional. Information about the agent provider, structured as {'organization': 'Provider Name', 'url': 'https://provider.url'}.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="service_url",
            field=models.URLField(
                help_text="The A2A service endpoint URL where this agent can be reached. Corresponds to AgentCard.url.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="agentskill",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional. A description of what the skill does. Corresponds to AgentSkill.description in AgentCard.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agentskill",
            name="examples",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional. Array of example prompts or use cases (strings) illustrating how to use this skill. Corresponds to AgentSkill.examples. Example: ['convert 100 USD to EUR', 'summarize this text: ...'].",
            ),
        ),
        migrations.AlterField(
            model_name="agentskill",
            name="input_modes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Supported input content types for this skill (array of MIME strings). Overrides agent default. Corresponds to AgentSkill.inputModes. Example: ["application/json", "text/plain"].',
            ),
        ),
        migrations.AlterField(
            model_name="agentskill",
            name="name",
            field=models.CharField(
                help_text="Human-readable name for the skill. Corresponds to AgentSkill.name in AgentCard.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="agentskill",
            name="output_modes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Supported output content types for this skill (array of MIME strings). Overrides agent default. Corresponds to AgentSkill.outputModes. Example: ["application/json", "text/plain"].',
            ),
        ),
        migrations.AlterField(
            model_name="agentskill",
            name="skill_id",
            field=models.CharField(
                help_text="Unique ID for the skill within the agent (e.g., 'generate-report', 'translate-text'). Corresponds to AgentSkill.id in AgentCard.",
                max_length=255,
            ),
        ),
    ]
