# Generated by Django 5.2 on 2025-05-21 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0006_agent_agent_software_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedExternalAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the external agent, from its card.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description from the agent card.",
                        null=True,
                    ),
                ),
                (
                    "service_url",
                    models.URLField(
                        help_text="The A2A service endpoint URL of the external agent.",
                        max_length=1024,
                    ),
                ),
                (
                    "card_url",
                    models.URLField(
                        blank=True,
                        db_index=True,
                        help_text="Optional. The URL from which this agent card was fetched. If provided, should be unique.",
                        max_length=1024,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "card_content",
                    models.JSONField(
                        blank=True,
                        help_text="A snapshot of the agent card JSON content.",
                        null=True,
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Capabilities like streaming, pushNotifications, stateTransitionHistory.",
                    ),
                ),
                (
                    "authentication_schemes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Authentication schemes supported by the external agent.",
                    ),
                ),
                (
                    "a2a_version",
                    models.CharField(
                        blank=True,
                        help_text="A2A protocol version claimed by the external agent.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("default_input_modes", models.JSONField(blank=True, default=list)),
                ("default_output_modes", models.JSONField(blank=True, default=list)),
                (
                    "skills_summary",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional summary of skills (e.g., list of skill names or IDs) for quick reference.",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this link is active and can be used for interactions.",
                    ),
                ),
                (
                    "last_successful_contact",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful interaction.",
                        null=True,
                    ),
                ),
                (
                    "last_failed_contact",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last failed interaction.",
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the last failed contact.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_by",
                    models.ForeignKey(
                        help_text="The user who linked this external agent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_external_agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Linked External Agent",
                "verbose_name_plural": "Linked External Agents",
                "ordering": ["linked_by", "name"],
                "unique_together": {("linked_by", "service_url")},
            },
        ),
    ]
