# Generated by Django 5.2 on 2025-04-29 03:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("gpt-3.5", "GPT-3.5"),
                            ("gpt-4", "GPT-4"),
                            ("claude-3", "Claude 3"),
                            ("gemini", "Gemini"),
                            ("custom", "自定义"),
                        ],
                        max_length=50,
                        verbose_name="Agent类型",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentCredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API密钥")),
                ("api_endpoint", models.URLField(blank=True, verbose_name="API端点")),
                (
                    "additional_params",
                    models.JSONField(blank=True, default=dict, verbose_name="附加参数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Agent凭证",
                "verbose_name_plural": "Agent凭证",
            },
        ),
    ]
