# Generated by Django 5.2 on 2025-04-29 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a2a_client", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("artifact_type", models.CharField(max_length=100, verbose_name="类型")),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "产物",
                "verbose_name_plural": "产物",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("agent", "代理")],
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterField(
            model_name="agent",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("gpt-3.5", "GPT-3.5"),
                    ("gpt-4", "GPT-4"),
                    ("claude-3", "Claude 3"),
                    ("gemini", "Gemini"),
                    ("custom", "自定义"),
                    ("a2a", "A2A兼容"),
                ],
                max_length=50,
                verbose_name="Agent类型",
            ),
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "part_type",
                    models.CharField(
                        choices=[("text", "文本"), ("data", "数据"), ("file", "文件")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="text/plain", max_length=100, verbose_name="内容类型"
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, null=True, verbose_name="文本内容"),
                ),
                (
                    "data_content",
                    models.JSONField(blank=True, null=True, verbose_name="数据内容"),
                ),
                (
                    "file_content",
                    models.BinaryField(blank=True, null=True, verbose_name="文件内容"),
                ),
                (
                    "file_uri",
                    models.URLField(blank=True, null=True, verbose_name="文件URI"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="a2a_client.artifact",
                        verbose_name="所属产物",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="a2a_client.message",
                        verbose_name="所属消息",
                    ),
                ),
            ],
            options={
                "verbose_name": "内容部分",
                "verbose_name_plural": "内容部分",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(blank=True, null=True, verbose_name="会话ID"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("working", "处理中"),
                            ("input-required", "需要输入"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("canceled", "已取消"),
                            ("unknown", "未知"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "error_details",
                    models.TextField(blank=True, null=True, verbose_name="错误详情"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="a2a_client.agent",
                        verbose_name="执行代理",
                    ),
                ),
                (
                    "client_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_tasks",
                        to="a2a_client.agent",
                        verbose_name="客户端代理",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="a2a_client.task",
                verbose_name="所属任务",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="a2a_client.task",
                verbose_name="所属任务",
            ),
        ),
    ]
