# Generated by Django 5.2 on 2025-05-07 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a2a_client", "0004_remove_task_session_id_alter_task_agent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="a2a_endpoint_url",
            field=models.URLField(blank=True, null=True, verbose_name="A2A端点URL"),
        ),
        migrations.AddField(
            model_name="agent",
            name="a2a_version",
            field=models.CharField(
                default="1.0.0", max_length=20, verbose_name="A2A版本"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="is_a2a_compliant",
            field=models.BooleanField(default=False, verbose_name="A2A协议兼容"),
        ),
        migrations.AddField(
            model_name="agentcredential",
            name="a2a_auth_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="A2A认证配置"),
        ),
        migrations.AddField(
            model_name="agentcredential",
            name="a2a_auth_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="A2A认证类型"
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="index",
            field=models.IntegerField(default=0, verbose_name="索引"),
        ),
        migrations.AddField(
            model_name="artifact",
            name="is_append",
            field=models.BooleanField(default=False, verbose_name="是否追加"),
        ),
        migrations.AddField(
            model_name="artifact",
            name="is_last_chunk",
            field=models.BooleanField(default=True, verbose_name="是否最后一块"),
        ),
        migrations.AddField(
            model_name="part",
            name="index",
            field=models.IntegerField(default=0, verbose_name="索引"),
        ),
        migrations.AddField(
            model_name="part",
            name="is_append",
            field=models.BooleanField(default=False, verbose_name="是否追加"),
        ),
        migrations.AddField(
            model_name="part",
            name="is_last_chunk",
            field=models.BooleanField(default=True, verbose_name="是否最后一块"),
        ),
        migrations.AddField(
            model_name="task",
            name="push_notification_config",
            field=models.JSONField(blank=True, null=True, verbose_name="推送通知配置"),
        ),
        migrations.CreateModel(
            name="AgentSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skill_id",
                    models.CharField(max_length=100, unique=True, verbose_name="技能ID"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="技能名称")),
                ("description", models.TextField(blank=True, verbose_name="技能描述")),
                ("input_modes", models.JSONField(default=list, verbose_name="输入模式")),
                ("output_modes", models.JSONField(default=list, verbose_name="输出模式")),
                ("examples", models.JSONField(default=list, verbose_name="示例")),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="参数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="a2a_client.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent技能",
                "verbose_name_plural": "Agent技能",
            },
        ),
        migrations.CreateModel(
            name="PushNotificationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(verbose_name="推送URL")),
                (
                    "token",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="推送令牌"
                    ),
                ),
                (
                    "auth_scheme",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="认证方案"
                    ),
                ),
                (
                    "auth_credentials",
                    models.TextField(blank=True, null=True, verbose_name="认证凭证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_config",
                        to="a2a_client.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "推送通知配置",
                "verbose_name_plural": "推送通知配置",
            },
        ),
    ]
