# Generated by Django 5.2 on 2025-05-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a2a_client", "0005_agent_a2a_endpoint_url_agent_a2a_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentskill",
            name="authentication_required",
            field=models.BooleanField(default=True, verbose_name="需要认证"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="authorization_hints",
            field=models.JSONField(blank=True, default=list, verbose_name="授权提示"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="rate_limits",
            field=models.JSONField(blank=True, default=dict, verbose_name="速率限制"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="scope",
            field=models.CharField(
                default="public", max_length=100, verbose_name="作用域"
            ),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="skill_type",
            field=models.CharField(
                default="general", max_length=100, verbose_name="技能类型"
            ),
        ),
    ]
