# Generated by Django 5.2 on 2025-05-07 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a2a_client", "0006_agentskill_authentication_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="a2a_contact",
            field=models.JSONField(blank=True, default=dict, verbose_name="联系信息"),
        ),
        migrations.AddField(
            model_name="agent",
            name="a2a_documentation_url",
            field=models.URLField(blank=True, null=True, verbose_name="文档URL"),
        ),
        migrations.AddField(
            model_name="agent",
            name="a2a_links",
            field=models.JSONField(blank=True, default=dict, verbose_name="相关链接"),
        ),
        migrations.AddField(
            model_name="agent",
            name="a2a_performance",
            field=models.JSONField(blank=True, default=dict, verbose_name="性能指标"),
        ),
        migrations.AddField(
            model_name="agent",
            name="a2a_provider",
            field=models.JSONField(blank=True, default=dict, verbose_name="提供商信息"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="additional_auth_scopes",
            field=models.JSONField(blank=True, default=list, verbose_name="额外授权范围"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="documentation_url",
            field=models.URLField(blank=True, null=True, verbose_name="文档URL"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="skill_settings",
            field=models.JSONField(blank=True, default=dict, verbose_name="技能设置"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="标签"),
        ),
        migrations.AddField(
            model_name="agentskill",
            name="version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="版本"
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="child_task_ids",
            field=models.JSONField(blank=True, default=list, verbose_name="子任务ID列表"),
        ),
        migrations.AddField(
            model_name="artifact",
            name="is_task_tree",
            field=models.BooleanField(default=False, verbose_name="是否任务树"),
        ),
        migrations.AddField(
            model_name="artifact",
            name="parent_task_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="父任务ID"),
        ),
        migrations.AddField(
            model_name="pushnotificationconfig",
            name="challenge_token",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL验证令牌"
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationconfig",
            name="challenge_verified",
            field=models.BooleanField(default=False, verbose_name="URL已验证"),
        ),
        migrations.AddField(
            model_name="pushnotificationconfig",
            name="max_retries",
            field=models.IntegerField(default=3, verbose_name="最大重试次数"),
        ),
        migrations.AddField(
            model_name="pushnotificationconfig",
            name="notification_types",
            field=models.JSONField(default=list, verbose_name="通知类型"),
        ),
        migrations.AddField(
            model_name="pushnotificationconfig",
            name="retry_delay",
            field=models.IntegerField(default=30, verbose_name="重试延迟(秒)"),
        ),
        migrations.CreateModel(
            name="TaskStateHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("submitted", "已提交"),
                            ("working", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("canceled", "已取消"),
                            ("input-required", "需要输入"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="前一状态"
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True, verbose_name="原因")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "initiated_by",
                    models.CharField(
                        blank=True,
                        help_text="状态变更的发起者，可以是用户ID、系统等",
                        max_length=255,
                        null=True,
                        verbose_name="发起者",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_history",
                        to="a2a_client.task",
                        verbose_name="所属任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务状态历史",
                "verbose_name_plural": "任务状态历史",
                "ordering": ["-timestamp"],
            },
        ),
    ]
