# Generated by Django 5.2 on 2025-05-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledgebase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
