# Generated by Django 5.2 on 2025-05-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledgebase", "0002_knowledgebase_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="original_file",
            field=models.FileField(
                blank=True, null=True, upload_to="knowledge_base_documents/%Y/%m/%d/"
            ),
        ),
    ]
