# Generated by Django 5.2 on 2025-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledgebase", "0003_document_extracted_text_document_original_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebase",
            name="is_public",
        ),
        migrations.AddField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="文件大小 (bytes)", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "公开"), ("PRIVATE", "私有 (仅限同一所有者的智能体)")],
                default="PRIVATE",
                help_text="控制知识库的可见性和访问权限",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True, help_text="如果处理失败，记录错误信息", null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="extracted_text",
            field=models.TextField(blank=True, help_text="从文档中提取的文本内容", null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_name",
            field=models.CharField(help_text="原始文件名或用户指定的名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="文件类型/扩展名, e.g., pdf, txt, docx", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="original_file",
            field=models.FileField(
                default=1,
                help_text="上传的原始文件",
                upload_to="knowledge_base_documents/%Y/%m/%d/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="processed_at",
            field=models.DateTimeField(blank=True, help_text="文档处理完成的时间", null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待处理"),
                    ("PROCESSING", "处理中"),
                    ("COMPLETED", "成功"),
                    ("FAILED", "失败"),
                ],
                default="PENDING",
                help_text="文档处理状态",
                max_length=20,
            ),
        ),
    ]
